name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test - Connected Component
      id: test-connected-component
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test - Connected Component
        setup-command: pip install scipy numpy pandas igraph jupytext nbconvert
        command: bash test/grade_notebook.sh tests/test_01.py assignment/assignment_example.ipynb
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-CONNECTED-COMPONENT_RESULTS: "${{steps.test-connected-component.outputs.result}}"
      with:
        runners: test-connected-component
